name: Revisao

on:
  push:
    branches: [ "master" ]
    
  workflow_dispatch:
  
env:
  Nome: Plamedi Pindi

jobs:
  Resivsao:
    runs-on: ubuntu-latest

    env:
      Proffission: Dev
      
    steps:
      - uses: actions/checkout@v4

      - name: Saudar
        run: echo "Hello, I'm $Name and I work as a $Proffision in $country"

        env:
          country: Brasil

