name: Revisao

on: 
  workflow_dispatch:
  
env:
  Name: Plamedi

jobs:
  Resivsao:
    runs-on: ubuntu-latest
    env:
      Proffission: Dev
      
    steps:
      - uses: actions/checkout@v4
      - name: Saudar
        run: echo "Hello, I'm $Name and I work as a $Proffission in $country. I'm certified at ${{CERTIFYED}}"
        env:
          country: Brasil

