name: Testing context variables

on:
  workflow_dispatch:

env:
 cloud: google-cloud

jobs:
  test_context_variables:
    runs-on: ubuntu-latest
    steps:
      - name: "Check Context Variables"
        run: |
          echo "Repository name : ${{ github.repository }}"
          echo "Workflow name : ${{ github.workflow }}"
          echo "triggered by : ${{ github.triggering_atcor }}"
