name: Testing workflow variables

on:
  workflow_dispatch:

env:
 cloud: google-cloud

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: Say hello
        run: echo "$Greeting $First_Name is using $cloud with project ${{vars.PROJECT_ID}}!" 
        env: 
          First_Name: Plamedi
